# Generated by Django 3.0.5 on 2020-06-29 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inscripcion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curp',
            fields=[
                ('pk_curp', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='CURP')),
                ('curp_ap_paterno', inscripcion.models.UpperCaseCharField(max_length=45, verbose_name='APELLIDO PATERNO')),
                ('curp_ap_materno', inscripcion.models.UpperCaseCharField(max_length=45, verbose_name='APELLIDO MATERNO')),
                ('curp_nombre', inscripcion.models.UpperCaseCharField(max_length=45, verbose_name='NOMBRE')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='FECHA DE CREACION')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='FECHA DE EDICION')),
                ('user', models.OneToOneField(max_length=18, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curp',
                'verbose_name_plural': 'Curp de alumnos',
                'db_table': 'Curp',
                'ordering': ['user', 'curp_ap_paterno'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_nom_esc', inscripcion.models.UpperCaseCharField(default='ESCUELA SECUNDARIA TECNICA INDUSTRIAL No 8', max_length=45, verbose_name='NOMBRE DE LA ESCUELA')),
                ('alumno_fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='FECHA DE NACIMIENTO')),
                ('alumno_sexo', inscripcion.models.UpperCaseCharField(blank=True, choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1, null=True, verbose_name='SEXO')),
                ('alumno_calle', inscripcion.models.UpperCaseCharField(blank=True, max_length=45, null=True, verbose_name='NOMBRE DE LA CALLE')),
                ('alumno_num_int', inscripcion.models.UpperCaseCharField(blank=True, max_length=6, null=True, verbose_name='NUM. INTERIOR')),
                ('alumno_num_ext', inscripcion.models.UpperCaseCharField(blank=True, max_length=6, null=True, verbose_name='NUM. EXTERIOR')),
                ('alumno_colonia', inscripcion.models.UpperCaseCharField(blank=True, max_length=45, null=True, verbose_name='NOMBRE DE LA COLONIA')),
                ('alumno_cp', models.CharField(blank=True, max_length=5, null=True, verbose_name='CODIGO POSTAL')),
                ('alumno_telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='TELEFONO')),
                ('alumno_nacionalidad', inscripcion.models.UpperCaseCharField(blank=True, default='MEXICANA', max_length=45, null=True, verbose_name='NACIONALIDAD')),
                ('alumno_entidad', inscripcion.models.UpperCaseCharField(blank=True, default='VERACRUZ', max_length=45, null=True, verbose_name='NOMBRE DE LA ENTIDAD')),
                ('alumno_municipio', inscripcion.models.UpperCaseCharField(blank=True, max_length=45, null=True, verbose_name='NOMBRE DEL MUNICIPIO')),
                ('alumno_localidad', inscripcion.models.UpperCaseCharField(blank=True, max_length=45, null=True, verbose_name='NOMBRE DE LA LOCALIDAD')),
                ('pk_curp', models.OneToOneField(max_length=18, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Curp')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'Alumno',
                'ordering': ['pk_curp', 'alumno_colonia'],
            },
        ),
    ]
