# Generated by Django 3.0.5 on 2020-06-30 18:53

from django.db import migrations, models
import django.db.models.deletion
import inscripcion.models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnogg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumnogg_grupo', inscripcion.models.UpperCaseCharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=1, verbose_name='LETRA')),
                ('alumnogg_turno', inscripcion.models.UpperCaseCharField(choices=[('MATUTINO', 'MATUTINO'), ('VESPERTINO', 'VESPERTINO')], default='MATUTINO', max_length=10, verbose_name='TURNO')),
                ('alumnogg_grado', inscripcion.models.UpperCaseCharField(choices=[('1', 'PRIMERO'), ('2', 'SEGUNDO'), ('3', 'TERCERO')], max_length=1, verbose_name='GRADO')),
                ('alumnogg_ciclo_escolar', inscripcion.models.UpperCaseCharField(default='2020-2021', max_length=9, verbose_name='CICLO ESCOLAR')),
                ('alumnogg_promedio', models.FloatField(blank=True, null=True, verbose_name='PROMEDIO DEL ALUMNO')),
                ('pk_curp', models.OneToOneField(max_length=18, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Curp')),
            ],
            options={
                'verbose_name': 'Grado y Grupo',
                'verbose_name_plural': 'Grado y Grupo de Alumnos',
                'db_table': 'Alumnogg',
                'ordering': ['pk_curp', 'alumnogg_grupo'],
            },
        ),
    ]
