# Generated by Django 3.0.5 on 2020-06-30 20:29

from django.db import migrations, models
import django.db.models.deletion
import inscripcion.models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_alumnogg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha_medica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fmedica_talla', models.FloatField(blank=True, null=True, verbose_name='ALTURA EN CM')),
                ('fmedica_peso', models.FloatField(blank=True, null=True, verbose_name='PESO EN KG')),
                ('fmedica_medida_cintura', models.FloatField(blank=True, null=True, verbose_name='MEDIDA DE LA CINTURA EN CM.')),
                ('fmedica_medida_cadera', models.FloatField(blank=True, null=True, verbose_name='MEDIDA DE LA CADERA EN CM')),
                ('fmedica_tipo_sangre', inscripcion.models.UpperCaseCharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, verbose_name='TIPO DE SANGRE')),
                ('fmedica_servicio_medico', inscripcion.models.UpperCaseCharField(choices=[('IMSS', 'IMSS'), ('ISSTE', 'ISSTE'), ('ISSFAM', 'ISSFAM'), ('SERVCIO MEDICO DE PEMEX', 'SERVCIO MEDICO DE PEMEX'), ('SEGURO POPULAR', 'SEGURO POPULAR'), ('SIN SEGURO', 'SIN SEGURO'), ('OTRO', 'OTRO')], max_length=25, verbose_name='SERVICIO MEDICO')),
                ('fmedica_educacion_especial', inscripcion.models.UpperCaseCharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, verbose_name='¿REQUIERE EDUCACION ESPECIAL?')),
                ('fmedica_es_alergico_medicamento', inscripcion.models.UpperCaseCharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, verbose_name='¿ES ALERGICO A ALGUN MEDICAMENTO?')),
                ('fmedica_cual_medicamento', inscripcion.models.UpperCaseCharField(max_length=40, verbose_name='¿CUAL MEDICAMENTO?')),
                ('fmedica_es_alergico_alimento', inscripcion.models.UpperCaseCharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, verbose_name='ES ALERGICO A ALGUN MEDICAMENTO?')),
                ('fmedica_cual_alimento', inscripcion.models.UpperCaseCharField(max_length=40, verbose_name='¿CUAL ALIMENTO?')),
                ('pk_curp', models.OneToOneField(max_length=18, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Curp')),
            ],
            options={
                'verbose_name': 'Ficha Medica general',
                'verbose_name_plural': 'Fichas medicas',
                'db_table': 'Ficha_medica',
                'ordering': ['pk_curp', 'fmedica_servicio_medico'],
            },
        ),
    ]
