# Generated by Django 3.0.5 on 2020-07-01 03:51

from django.db import migrations, models
import django.db.models.deletion
import inscripcion.models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_ficha_medica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_medica',
            name='fmedica_cual_alimento',
            field=inscripcion.models.UpperCaseCharField(blank=True, max_length=40, null=True, verbose_name='¿CUAL ALIMENTO?'),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='fmedica_cual_medicamento',
            field=inscripcion.models.UpperCaseCharField(blank=True, max_length=40, null=True, verbose_name='¿CUAL MEDICAMENTO?'),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='fmedica_educacion_especial',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿REQUIERE EDUCACION ESPECIAL?'),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='fmedica_es_alergico_alimento',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='ES ALERGICO A ALGUN ALIMENTO?'),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='fmedica_es_alergico_medicamento',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿ES ALERGICO A ALGUN MEDICAMENTO?'),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='fmedica_servicio_medico',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('IMSS', 'IMSS'), ('ISSTE', 'ISSTE'), ('ISSFAM', 'ISSFAM'), ('SERVCIO MEDICO DE PEMEX', 'SERVCIO MEDICO DE PEMEX'), ('SEGURO POPULAR', 'SEGURO POPULAR'), ('SIN SEGURO', 'SIN SEGURO'), ('OTRO', 'OTRO')], max_length=25, null=True, verbose_name='SERVICIO MEDICO'),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='fmedica_tipo_sangre',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True, verbose_name='TIPO DE SANGRE'),
        ),
        migrations.CreateModel(
            name='Ficha_medica_visual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fvisual_ojo_izquierdo_num_linea', models.IntegerField(blank=True, null=True, verbose_name='OJO IZQUIERDO NUMERO DE LINEA')),
                ('fvisual_ojo_derecho_num_linea', models.IntegerField(blank=True, null=True, verbose_name='OJO DERECHO NUMERO DE LINEA')),
                ('fvisual_usa_lentes', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿USA LENTES?')),
                ('pk_curp', models.OneToOneField(max_length=18, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Curp')),
            ],
            options={
                'verbose_name': 'Ficha Medica Visual',
                'verbose_name_plural': 'Fichas medicas visuales',
                'db_table': 'Ficha_medica_visual',
                'ordering': ['pk_curp', 'fvisual_usa_lentes'],
            },
        ),
        migrations.CreateModel(
            name='Ficha_medica_dental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdental_tiene_caries', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE CARIES?')),
                ('fdental_numero_caries', models.IntegerField(blank=True, null=True, verbose_name='NUMERO DE CARIES')),
                ('fdental_tiene_inflamacion_o_sangrado_al_cepillarse', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE INFLAMACION O SANGRADO AL CEPILLARSE?')),
                ('fdental_tiene_dientes_chuecos_malaposicion', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE DIENTES CHUECOS O EN MALA POSICION?')),
                ('pk_curp', models.OneToOneField(max_length=18, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Curp')),
            ],
            options={
                'verbose_name': 'Ficha Medica Dental',
                'verbose_name_plural': 'Fichas medicas dentales',
                'db_table': 'Ficha_medica_dental',
                'ordering': ['pk_curp', 'fdental_tiene_caries'],
            },
        ),
        migrations.CreateModel(
            name='Ficha_medica_auditiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fauditiva_agudeza_oido_izquierdo', inscripcion.models.UpperCaseCharField(blank=True, choices=[('TA', 'TRANSMISION AÉREA'), ('TO', 'TRANSMISION ÓSEA')], max_length=2, null=True, verbose_name='TIPO DE TRANSMISION DEL OIDO IZQUIERDO')),
                ('fauditiva_agudeza_oido_derecho', inscripcion.models.UpperCaseCharField(blank=True, choices=[('TA', 'TRANSMISION AÉREA'), ('TO', 'TRANSMISION ÓSEA')], max_length=2, null=True, verbose_name='TIPO DE TRANSMISION DEL OIDO DERECHO')),
                ('fauditiva_usa_aparato_oido_izquierdo', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿USA APARATO EN EL OIDO IZQUIERDO?')),
                ('fauditiva_usa_aparato_oido_derecho', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿USA APARATO EN EL OIDO DERECHO?')),
                ('pk_curp', models.OneToOneField(max_length=18, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Curp')),
            ],
            options={
                'verbose_name': 'Ficha Medica auditiva',
                'verbose_name_plural': 'Fichas medicas auditivas',
                'db_table': 'Ficha_medica_auditiva',
                'ordering': ['pk_curp'],
            },
        ),
        migrations.CreateModel(
            name='Alumno_bajo_tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atratamiento_problema_postural', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE PROBLEMA POSTURAL?')),
                ('atratamiento_tiene_cardiopatias', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE CARDIOPATIAS ?')),
                ('atratamiento_tiene_hipertension', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE HIPERTENSIÓN?')),
                ('atratamiento_tiene_cancer', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE CANCER?')),
                ('atratamiento_tiene_obesidad', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE OBESIDAD?')),
                ('atratamiento_tiene_desnutricion', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE DESNUTRICIÓN?')),
                ('atratamiento_tiene_VIH_sida', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE VIH SIDA?')),
                ('atratamiento_tiene_asma', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE ASMA?')),
                ('atratamiento_tiene_depresion', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE DEPRESION?')),
                ('atratamiento_tiene_lupus', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE LUPUS?')),
                ('atratamiento_tiene_insuficiencia_renal', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE INSUFICIENCIA RENAL?')),
                ('atratamiento_tiene_artritis', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE PROBLEMA ARTRITIS?')),
                ('atratamiento_tiene_epilepsia_o_convulsiones', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE EPILEPSIA O CONVULSIONES?')),
                ('atratamiento_tiene_tuberculosis', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE TUBERCULOSIS?')),
                ('atratamiento_tiene_otras_enfermedades_cronicas', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE ALGUNA OTRA ENFERMEDAD CRoNICA?')),
                ('pk_curp', models.OneToOneField(max_length=18, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Curp')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'db_table': 'Alumno_bajo_tratamiento',
                'ordering': ['pk_curp'],
            },
        ),
    ]
