# Generated by Django 3.0.5 on 2020-07-01 21:37

from django.db import migrations, models
import django.db.models.deletion
import inscripcion.models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_auto_20200630_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno_bajo_tratamiento',
            name='atratamiento_problema_postural',
        ),
        migrations.AddField(
            model_name='ficha_medica',
            name='fmedica_problema_postural',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿TIENE PROBLEMA POSTURAL?'),
        ),
        migrations.AddField(
            model_name='ficha_medica',
            name='fmedica_usa_aparato_ortopedico',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿UTILIZA APARATO ORTOPEDICO?'),
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discapacidad_tiene_autismo', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE AUTISMO?')),
                ('discapacidad_tiene_baja_vision', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE BAJA VISIÓN?')),
                ('discapacidad_tiene_ceguera', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE CEGUERA?')),
                ('discapacidad_intelectual', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE DISCAPACIDAD INTELECTUAL?')),
                ('discapacidad_motriz', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE DISCAPACIDAD MOTRIZ?')),
                ('discapacidad_multiple', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE DISCAPACIDAD MULTIPLE?')),
                ('discapacidad_tiene_baja_audicion', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE BAJA AUDICIÓN?')),
                ('discapacidad_mental', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE DISCAPACIDAD MENTAL?')),
                ('discapacidad_tiene_problema_comunicacion_lenguaje', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE PROBLEMAS DE COMUNICACION O LENGUAJE?')),
                ('discapacidad_tiene_problema_conducta', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE PROBLEMAS DE CONDUCTA?')),
                ('discapacidad_tiene_sordera', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE SORDERA?')),
                ('discapacidad_tiene_sordoceguera', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE SORDOCEGUERA?')),
                ('discapacidad_tiene_transtorno_del_desarrollo', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE TRANSTORNO DEL DESARROLLO?')),
                ('discapacidad_tiene_transtorno_deficit_atencion_hiperactividad', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE TRANSTORNO DE DEFICIT DE ATENCION O HIPERACTIVIDAD?')),
                ('pk_curp', models.OneToOneField(max_length=18, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Curp')),
            ],
            options={
                'verbose_name': 'Discapacidad',
                'verbose_name_plural': 'Discapacidades',
                'db_table': 'Discapacidad',
                'ordering': ['pk_curp'],
            },
        ),
        migrations.CreateModel(
            name='Datos_familiares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcasa_padres', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿VIVES CON TUS PADRES?')),
                ('pcasa_madre', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿VIVES CON TU MADRE?')),
                ('pcasa_padre', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿VIVES CON TU PADRE?')),
                ('pcasa_hermanos', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿VIVES CON HERMANOS?')),
                ('pcasa_abuelos', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿VIVES CON TUS ABUELOS?')),
                ('pcasa_tios', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿VIVES CON TUS TIOS?')),
                ('pcasa_otro', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='OTRO(A)')),
                ('pcasa_solo', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿VIVES SOLO?')),
                ('pk_curp', models.OneToOneField(max_length=18, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Curp')),
            ],
            options={
                'verbose_name': 'Dato Familiar',
                'verbose_name_plural': 'Datos Familiares',
                'db_table': 'Datos_familiares',
                'ordering': ['pk_curp'],
            },
        ),
        migrations.CreateModel(
            name='Aptitud_sobresaliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptitud_intelectual', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE APTITUD INTELECTUAL?')),
                ('aptitud_psicomotriz', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE APTITUD PSICOMOTRIZ?')),
                ('aptitud_socioafectiva', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE APTITUD SOCIOAFECTIVA?')),
                ('aptitud_creativa', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE APTITUD CREATIVA?')),
                ('pk_curp', models.OneToOneField(max_length=18, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Curp')),
            ],
            options={
                'verbose_name': 'Aptitud',
                'verbose_name_plural': 'Aptitudes',
                'db_table': 'Aptitud_sobresaliente',
                'ordering': ['pk_curp'],
            },
        ),
        migrations.CreateModel(
            name='Alumno_convivencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pconvive_padres', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿PASAS LA MAYOR PARTE DEL TIEMPO CON TUS PADRES?')),
                ('pconvive_madre', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='PASAS LA MAYOR PARTE DEL TIEMPO CON TU MADRE')),
                ('pconvive_padre', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='PASAS LA MAYOR PARTE DEL TIEMPO CON TU PADRE')),
                ('pconvive_hermanos', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='PASAS LA MAYOR PARTE DEL TIEMPO CON TUS HERMANOS')),
                ('pconvive_abuelos', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='PASAS LA MAYOR PARTE DEL TIEMPO CON TUS ABUELOS')),
                ('pconvive_tios', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='PASAS LA MAYOR PARTE DEL TIEMPO CON TUS TIOS')),
                ('pconvive_otro', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='PASAS LA MAYOR PARTE DEL TIEMPO CON OTROS')),
                ('pconvive_solo', inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='PASAS LA MAYOR PARTE DEL TIEMPO SOLO')),
                ('pconvive_numero_hermanos', models.IntegerField(blank=True, null=True, verbose_name='¿CUANTOS HERMANOS TIENES?')),
                ('pconvive_lugar_entre_hermanos', models.IntegerField(blank=True, null=True, verbose_name='¿CUAl ES TU LUGAR ENTRE HERMANOS?')),
                ('pconvive_actividad_dedica_mas_tiempo', inscripcion.models.UpperCaseCharField(choices=[('JUGAR', 'JUGAR'), ('HACER ALGUN DEPORTE', 'HACER ALGUN DEPORTE'), ('HACER TAREA', 'HACER TAREA'), ('UTILIZAR UN APARATO ELECTRONICO', 'UTILIZAR UN APARATO ELECTRONICO'), ('SALIR CON AMIGOS', 'SALIR CON AMIGOS'), ('TRABAJAR', 'TRABAJAR'), ('HACER TAREAS DOMESTICAS', 'HACER TAREAS DOMESTICAS'), ('OTROS', 'OTROS')], max_length=35, null=True, verbose_name='¿A QUÉ ACTIVIDAD LE DEDICAS MAS TIEMPO?')),
                ('pk_curp', models.OneToOneField(max_length=18, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Curp')),
            ],
            options={
                'verbose_name': 'Convivencia',
                'verbose_name_plural': 'Convivencias',
                'db_table': 'Alumno_convivencia',
                'ordering': ['pk_curp'],
            },
        ),
        migrations.CreateModel(
            name='Acta_nacimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_nacimiento_numero_control_o_folio', inscripcion.models.UpperCaseCharField(blank=True, max_length=40, null=True, verbose_name='NUMERO DE CONTROL O FOLIO DEL ACTA')),
                ('acta_nacimiento_numero_libro', inscripcion.models.UpperCaseCharField(blank=True, max_length=40, null=True, verbose_name='NUMERO DEL LIBRO')),
                ('acta_nacimiento_año_registro', inscripcion.models.UpperCaseCharField(blank=True, max_length=4, null=True, verbose_name='AÑO DE REGISTRO')),
                ('acta_nacimiento_numero_acta', inscripcion.models.UpperCaseCharField(blank=True, max_length=40, null=True, verbose_name='NUMERO DE ACTA')),
                ('pk_curp', models.OneToOneField(max_length=18, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Curp')),
            ],
            options={
                'verbose_name': 'Acta de nacimiento',
                'verbose_name_plural': 'Datos del acta',
                'db_table': 'Acta_nacimiento',
                'ordering': ['pk_curp'],
            },
        ),
    ]
