# Generated by Django 3.0.5 on 2020-07-02 00:48

from django.db import migrations
import inscripcion.models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0005_auto_20200701_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta_nacimiento',
            name='acta_nacimiento_folio_curp',
            field=inscripcion.models.UpperCaseCharField(blank=True, max_length=40, null=True, verbose_name='NUMERO DE FOLIO DEL CURP'),
        ),
        migrations.AddField(
            model_name='alumno_bajo_tratamiento',
            name='atratamiento_tiene_diabetes',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿TIENE DIABETES?'),
        ),
    ]
