# Generated by Django 3.0.5 on 2020-07-03 03:29

from django.db import migrations
import inscripcion.models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0008_auto_20200702_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno_convivencia',
            name='pconvive_abuelos',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='PASAS LA MAYOR PARTE DEL TIEMPO CON TUS ABUELOS'),
        ),
        migrations.AlterField(
            model_name='alumno_convivencia',
            name='pconvive_hermanos',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='PASAS LA MAYOR PARTE DEL TIEMPO CON TUS HERMANOS'),
        ),
        migrations.AlterField(
            model_name='alumno_convivencia',
            name='pconvive_madre',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='PASAS LA MAYOR PARTE DEL TIEMPO CON TU MADRE'),
        ),
        migrations.AlterField(
            model_name='alumno_convivencia',
            name='pconvive_otro',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='PASAS LA MAYOR PARTE DEL TIEMPO CON OTROS'),
        ),
        migrations.AlterField(
            model_name='alumno_convivencia',
            name='pconvive_padre',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='PASAS LA MAYOR PARTE DEL TIEMPO CON TU PADRE'),
        ),
        migrations.AlterField(
            model_name='alumno_convivencia',
            name='pconvive_padres',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿PASAS LA MAYOR PARTE DEL TIEMPO CON TUS PADRES?'),
        ),
        migrations.AlterField(
            model_name='alumno_convivencia',
            name='pconvive_solo',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='PASAS LA MAYOR PARTE DEL TIEMPO SOLO'),
        ),
        migrations.AlterField(
            model_name='alumno_convivencia',
            name='pconvive_tios',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='PASAS LA MAYOR PARTE DEL TIEMPO CON TUS TIOS'),
        ),
        migrations.AlterField(
            model_name='aptitud_sobresaliente',
            name='aptitud_creativa',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿TIENE APTITUD CREATIVA?'),
        ),
        migrations.AlterField(
            model_name='aptitud_sobresaliente',
            name='aptitud_intelectual',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿TIENE APTITUD INTELECTUAL?'),
        ),
        migrations.AlterField(
            model_name='aptitud_sobresaliente',
            name='aptitud_psicomotriz',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿TIENE APTITUD PSICOMOTRIZ?'),
        ),
        migrations.AlterField(
            model_name='aptitud_sobresaliente',
            name='aptitud_socioafectiva',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿TIENE APTITUD SOCIOAFECTIVA?'),
        ),
        migrations.AlterField(
            model_name='datos_familiares',
            name='pcasa_abuelos',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿VIVES CON TUS ABUELOS?'),
        ),
        migrations.AlterField(
            model_name='datos_familiares',
            name='pcasa_hermanos',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿VIVES CON HERMANOS?'),
        ),
        migrations.AlterField(
            model_name='datos_familiares',
            name='pcasa_madre',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿VIVES CON TU MADRE?'),
        ),
        migrations.AlterField(
            model_name='datos_familiares',
            name='pcasa_otro',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='OTRO(A)'),
        ),
        migrations.AlterField(
            model_name='datos_familiares',
            name='pcasa_padre',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿VIVES CON TU PADRE?'),
        ),
        migrations.AlterField(
            model_name='datos_familiares',
            name='pcasa_padres',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿VIVES CON TUS PADRES?'),
        ),
        migrations.AlterField(
            model_name='datos_familiares',
            name='pcasa_solo',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿VIVES SOLO?'),
        ),
        migrations.AlterField(
            model_name='datos_familiares',
            name='pcasa_tios',
            field=inscripcion.models.UpperCaseCharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿VIVES CON TUS TIOS?'),
        ),
    ]
